version: '3.8'

services:
  mongodb-4.4-1:
    image: mongo:4.4
    container_name: mongodb-4.4-1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 27017:27017
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "/docker-entrypoint-initdb.d/rs-init.sh"]
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs"]
    depends_on:
      - mongodb-4.4-2
      - mongodb-4.4-3
    links:
      - mongodb-4.4-2
      - mongodb-4.4-3
  mongodb-4.4-2:
    image: mongo:4.4
    container_name: mongodb-4.4-2
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 27018:27017
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs"]
  mongodb-4.4-3:
    image: mongo:4.4
    container_name: mongodb-4.4-3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 27019:27017
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs"]